### ISSUE TITLE
[Modules] Kibana settings no longer default to plain text, contradicting documentation

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#10059]
Versions: Logstash 6.4.1+

While trying to setup modules, using the following command:

```
bin/logstash --modules arcsight --setup
```

and the following configuration:

```
modules:
  - name: arcsight
    var.inputs: 'eventbroker'
    var.input.eventbroker.bootstrap_servers: "localhost:9092"                                                                                                                         
    var.elasticsearch.username: 'elastic'
    var.elasticsearch.password: 'XXXX'
    var.kibana.username: 'elastic'
    var.kibana.password: 'XXXX'
```

Logstash will attempt to connect to Elasticsearch over plaintext, and Kibana over SSL, causing the following error when attempting to connect to plaintext instances of each:
```
[2018-10-22T15:53:45,221][ERROR][logstash.modules.kibanaclient] Error when executing Kibana client request {:error=>#<Manticore::UnknownException: Unrecognized SSL message, plaintext connection?>}
```

Kibana connecting over SSL does not match the [default value in the documentation](https://www.elastic.co/guide/en/logstash/current/arcsight-module.html#arcsight-module-config):

This can be mitigated by adding the setting:
```
var.kibana.ssl.enabled: false
```
