### ISSUE TITLE
Unnecessary [host] field added when using Beats input causes mapping conflicts.

### ISSUE THREAD

**Issue by ceeeekay** [elastic/logstash#10054]
I don't know if this issue is libbeat, or logstash-plugins, so I'm opening it under Logstash.

A bit of history: We're still trying to deal with the introduction of the [host] object from the Elastic Common Schema, however [beats #7528](https://github.com/elastic/beats/issues/7528) is preventing us from name spacing our custom fields properly (and there has been no action on that issue for months). So we're stuck using many workarounds.

We're using a processor to fields in the mean time as per [this discuss thread](https://discuss.elastic.co/t/logstash-errors-after-upgrading-to-filebeat-6-3-0/135984/16) so we can at least ship data while we transition everything to the new schema, without Beats client upgrades breaking our mappings.

However, we can't even begin to move to new mappings including the [host] obect, because if this object doesn't exist in the orignal message, the Beats input cheerily adds an old-style [host] *field* to the message, which is incompatible with recent changes to index mappings. The end result is we're forced to have mapping conflicts and dropped messages while trying to transition to the new schema.

I can't overstate how bad this is.

I'm assuming this behaviour has been masked because if a [host] object exists in the message, the Beats input can't add a host field.

Can we please stop this from happening? It's making any sort of move to the new schema basically impossible.

- Version: 6.4.2
- Operating System: Ubuntu 18.04.1
- Sample Data: Anything
- Steps to Reproduce: Use the below configs with the rename processor and observe the [host] field in the output.
- Config File (if you have sensitive info, please remove it):

**Filebeat**
```
filebeat:
  registry_file: /var/lib/filebeat/registry
  config.prospectors:
    enabled: true
    path: /etc/filebeat/conf.d/*.yml
filebeat.inputs:
  - type: log
    paths:
      - /tmp/test.txt
output:
  logstash:
    hosts: ["localhost:10514"]
    compression_level: 3
processors:
  - rename:
      fields:
       - from: "host"
         to: "node"
```

**Logstash**
```
input { 
  beats { 
    port => 10514
  } 
}

output { 
  stdout {
    codec => rubydebug
  }
}
```

**Filebeat output**
```
Publish event: {
  "@timestamp": "2018-10-17T22:56:27.903Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "doc",
    "version": "6.4.2"
  },
  "offset": 6,
  "message": "hi",
  "input": {
    "type": "log"
  },
  "prospector": {
    "type": "log"
  },
  "node": {
    "name": "civet"
  },
  "beat": {
    "name": "civet",
    "hostname": "civet",
    "version": "6.4.2"
  },
  "source": "/tmp/test.txt"
}
```

**Logstash output** (note: this contains *"host" => "civet"*) which is not in the original message.
```
{
          "beat" => {
         "version" => "6.4.2",
        "hostname" => "civet",
            "name" => "civet"
    },
         "input" => {
        "type" => "log"
    },
          "node" => {
        "name" => "civet"
    },
       "message" => "hi",
    "@timestamp" => 2018-10-17T22:56:27.903Z,
        "offset" => 6,
          "tags" => [
        [0] "beats_input_codec_plain_applied"
    ],
    "prospector" => {
        "type" => "log"
    },
          "host" => "civet",
        "source" => "/tmp/test.txt",
      "@version" => "1"
}
```
