### ISSUE TITLE
Azure Monitor Kibana configuration always seems to send over SSL

### ISSUE THREAD

**Issue by russcam** [elastic/logstash#10125]
I've added a PowerShell script to configuring setting up of Azure monitor module with Elastic's ARM template offering:

https://github.com/elastic/azure-marketplace-examples/blob/master/azure_monitor_logstash/azure_monitor_logstash.ps1

One issue that I ran into is that the Kibana configuration always seems to want to send the Dashboards to Kibana over SSL. For example, the following configurations for kibana in logstash.yml exhibit the subsequent error message:

```yml
modules:
  - name: azure
    # other settings skipped for brevity
    var.kibana.host: "kibana:5601"
    var.kibana.username: elastic
    var.kibana.password: "<password>"
```

```yml
modules:
  - name: azure
    # other settings skipped for brevity
    var.kibana.host: "http://kibana:5601"
    var.kibana.username: elastic
    var.kibana.password: "<password>"
```

```yml
modules:
  - name: azure
    # other settings skipped for brevity
    var.kibana.host: "kibana:5601"
    var.kibana.scheme: http
    var.kibana.username: elastic
    var.kibana.password: "<password>"
```

```
[2018-11-07T01:14:11,380][ERROR][logstash.modules.kibanaclient] Error when executing Kibana client request {:error=>#<Manticore::UnknownException: Unrecognized SSL message, plaintext connection?>}
[2018-11-07T01:14:11,586][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>LogStash::ConfigLoadingError, :message=>"Failed to import module configurations to Elasticsearch and/or Kibana. Module: azure has Elasticsearch hosts: [\"http://10.0.0.4:9200\"] and Kibana hosts: [\"kibana:5601\"]", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/config/modules_common.rb:108:in `block in pipeline_configs'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/config/modules_common.rb:54:in `pipeline_configs'", "/usr/share/logstash/logstash-core/lib/logstash/config/source/modules.rb:14:in `pipeline_configs'", "/usr/share/logstash/logstash-core/lib/logstash/config/source_loader.rb:61:in `block in fetch'", "org/jruby/RubyArray.java:2481:in `collect'", "/usr/share/logstash/logstash-core/lib/logstash/config/source_loader.rb:60:in `fetch'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:142:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:93:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```
Explicitly setting `var.kibana.ssl.enabled: false` **did work**

```yml
modules:
  - name: azure
    # other settings skipped for brevity
    var.kibana.host: "kibana:5601"
    var.kibana.ssl.enabled: false
    var.kibana.username: elastic
    var.kibana.password: "<password>"
```

It looks like it may be related to the following

https://github.com/elastic/logstash/blob/796eb3e4b3c4d87eac9cc820d00387a845a46042/logstash-core/lib/logstash/modules/kibana_client.rb#L43-L73
