### ISSUE TITLE
FileBeat Ignores enabled setting in prospector config

### ISSUE THREAD

**Issue by cawoodm** [elastic/logstash#10514]
FileBeat 6.6.1 / Windows (ES 6.5)

FileBeat is watching folders which we have disabled by setting `enabled: false` in the prospector's `.yml` configuration.

This may not be a BUG per se but it's confusing.

### filebeat.yml:
```
filebeat.config.prospectors:
  enabled: true
  path: D:\elk\filebeat\config\*access_prod.yml
```

### config\filebeat_access_prod.yml:
```
# Parse app02 apache tomcat "access" log
- type: log
  enabled: false
  paths:
    - D:\app02-logs\tomcat\access.*.log
```

As we can see it is watching the disabled folder:
![image](https://user-images.githubusercontent.com/498834/53791439-b71f4680-3f29-11e9-812c-48c21ac8b176.png)

And picking up files there:
![image](https://user-images.githubusercontent.com/498834/53791471-c900e980-3f29-11e9-9110-c2734f2a5fbc.png)
