### ISSUE TITLE
Rejecting mapping update when loading data with arcsight module

### ISSUE THREAD

**Issue by DanRoscigno** [elastic/logstash#10613]
I am seeing this with version 7.0.0-rc1 (Elasticsearch, Logstash, and Kibana all same version, and all running on the same box):

```[2019-03-29T01:53:11,741][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"arcsight-2017.06.11", :_type=>"syslog", :routing=>nil}, #<LogStash::Event:0x540cac10>], :response=>{"index"=>{"_index"=>"arcsight-2017.06.11", "_type"=>"syslog", "_id"=>"KgMmx2kBMeFMtNoPnBj8", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [arcsight-2017.06.11] as the final mapping would have more than 1 type: [_doc, syslog]"}}}}```

For all general issues, please provide the following details for fast resolution:

- Version: 7.0.0-RC1
- Operating System: Linux 64 bit
- Config File:
This is my complete logstash.yml:
```
modules:
  - name: arcsight
    var.inputs: smartconnector
    var.input.smartconnector.port: 5000
    var.elasticsearch.hosts: http://127.0.0.1:9200
    var.elasticsearch.username: elastic
    var.elasticsearch.password: changeme
    var.kibana.host: roscigno-demo:5601
    var.kibana.username: elastic
    var.kibana.password: changeme
    var.elasticsearch.ssl.enabled: false
    var.kibana.scheme: http
    var.kibana.ssl.enabled: false
    var.kibana.ssl.verification_mode: disable
```

- Sample Data: File from [elastic/examples](https://github.com/elastic/examples/blob/master/Security%20Analytics/auditd_analysis/example_1/auditd.cef)
- Steps to Reproduce:
### Elasticsearch setup
Run it straight out of the box, no configuration

### Kibana setup
This is my complete config/kibana.yml:
```
server.host: "roscigno-demo"
```

### Edit config/logstash.yml
This is my complete logstash.yml:
```
modules:
  - name: arcsight
    var.inputs: smartconnector
    var.input.smartconnector.port: 5000
    var.elasticsearch.hosts: http://127.0.0.1:9200
    var.elasticsearch.username: elastic
    var.elasticsearch.password: changeme
    var.kibana.host: roscigno-demo:5601
    var.kibana.username: elastic
    var.kibana.password: changeme
    var.elasticsearch.ssl.enabled: false
    var.kibana.scheme: http
    var.kibana.ssl.enabled: false
    var.kibana.ssl.verification_mode: disable
```

### Load the index pattern, dashboards, etc.
Run logstash with the setup arg:
```
./bin/logstash --modules arcsight --setup
```

Note: I expected this to run just the setup, but it runs the setup and then listens on port 5000 (arcsight.var.input.smartconnector.port).  So CTRL-C if you want to stop it.

### Run Logstash listening for ArcSight connections
If you did CTRL-C and now want to run Logstash listening for ArcSight connections, just drop the `--setup`:
```
./bin/logstash --modules arcsight
```

### If you are sending in a CEF file through netcat:
```
cat auditd.cef | nc localhost 5000
```
