### ISSUE TITLE
Multiple pipelines with xpack management not working

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#10898]
I have Logstash in Kuberenetes (abbreviated config shown):

```
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.2.3
        env:
          - name: XPACK_MANAGEMENT_PIPELINE_ID
            value: "infosec-cloudtrail"
          - name: XPACK_MANAGEMENT_ENABLED
            value: "true"
```

When executing, this creates a `logstash.yml` with the following (observed with `kubectl exec logstash ...`):

```
xpack.management.pipeline.id: infosec-cloudtrail,beats
```

This seems incorrect, I think it should use a list in YAML syntax:

```
xpack.management.pipeline.id: [ "infosec-cloudtrail", "beats" ]
```

I don't know if we have any automated way of telling env2yaml that a given setting is an array.

-----

I'm going to work around this by shipping my own logstash.yml (mainly because it'll be simpler in k8s because every ENV var in k8s is minimum 2 yaml lines (often 5 if using a secret).
