### ISSUE TITLE
Netflow module one-time dashboard setup via docker?

### ISSUE THREAD

**Issue by sgreszcz** [elastic/logstash#10982]
It is not well documented on how to trigger the "--setup" for kibana netflow dashboards using the new netflow module as described here: https://www.elastic.co/guide/en/logstash/current/netflow-module.html

From the cli you can run "bin/logstash --modules netflow --setup -M netflow.var.input.udp.port=NNNN"

However it is not clear on how to pass through the --setup as an environment variable, say using docker-compse.

For all general issues, please provide the following details for fast resolution:

- Version: 7.2
- Operating System:  Ubuntu 18.04 LTS
- Config File 
modules:

- name: netflow
  var.elasticsearch.hosts: "elk-alln-001"
  var.input.udp.port: 2055
  var.kibana.host: "elk-alln-001"

Netlfow is being collected ok and can be seen in Kibana, however I cannot get the kibana dashboards to provision.

**Comment by yaauie** [comment]
It _looks_ like setting the config value `modules_setup: true` in your `logstash.yml` should work.

1. Setup is done [if the `modules_setup` setting is true](https://github.com/elastic/logstash/blob/v7.2.0/logstash-core/lib/logstash/config/modules_common.rb#L76)
2. The command-line flag `--setup` [is backed by the `modules_setup` setting](https://github.com/elastic/logstash/blob/v7.2.0/logstash-core/lib/logstash/runner.rb#L87-L90)

**Comment by sgreszcz** [comment]
> It _looks_ like setting the config value `modules_setup: true` in your `logstash.yml` should work.
> 
> 1. Module setup is done [if the `modules_setup` setting is true](https://github.com/elastic/logstash/blob/v7.2.0/logstash-core/lib/logstash/config/modules_common.rb#L76)
> 2. The command-line flag `--setup` [is backed by the `modules_setup` setting](https://github.com/elastic/logstash/blob/v7.2.0/logstash-core/lib/logstash/runner.rb#L87-L90)

Still doesn't work with the logstash.yml

modules:
- name: netflow
  var.elasticsearch.hosts: "elk-alln-001"
  var.input.udp.port: 2055
  var.kibana.host: "elk-alln-001"
  modules_setup : true

**Comment by huliz** [comment]
Make sure you put the modules_setup in the right place. You should also explicitly disable ssl.

```
http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
modules_setup: true

modules:
  - name: netflow
    var.input.udp.port: 9995
    var.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    var.elasticsearch.ssl.enabled: false
    var.kibana.host: kibanaip:5601
    var.kibana.scheme: http
    var.kibana.ssl.enabled: false
    var.kibana.ssl.verification_mode: disable
```
