### ISSUE TITLE
Expand environment variables in pipelines.yml

### ISSUE THREAD

**Issue by jarpy** [elastic/logstash#11064]
The ability to use environment variables in `logstash.yml` is fantastic; it's a bit of a game-changer for container environments.

It would be great if `pipelines.yml` could get the same treatment.

I'd like to do this:

```yaml
- pipeline.id: ${LLAMA_RELEASE}-input
  path.config: "/usr/share/logstash/pipeline/input.conf"
  pipeline.workers: 1

- pipeline.id: ${LLAMA_RELEASE}-riemann
  path.config: "/usr/share/logstash/pipeline/riemann.conf"
  pipeline.workers: 1

- pipeline.id: ${LLAMA_RELEASE}-elasticsearch
  path.config: "/usr/share/logstash/pipeline/elasticsearch.conf"
  pipeline.workers: 2
  queue.type: persisted
```

But that results in pipeline IDs like this:

![image](https://user-images.githubusercontent.com/119659/63402084-2e379100-c41d-11e9-994e-6eef49b7dfe8.png)
