### ISSUE TITLE
config auto reload doesn't print logs if the pipeline is removed and added again

### ISSUE THREAD

**Issue by chanjarster** [elastic/logstash#12048]
- Version: 7.8.0
- Operating System: Docker
- Config File (if you have sensitive info, please remove it):

config/logstash.yml:

```yaml
http.host: "0.0.0.0"
config.reload.automatic: true
```

config/pipelines.yml:

```yaml
- pipeline.id: ns-1-app-1
  path.config: "/usr/share/logstash/pipeline/ns-1-app-1.conf"
- pipeline.id: ns-1-app-2
  path.config: "/usr/share/logstash/pipeline/ns-1-app-2.conf"
```

pipeline/ns-1-app-1.conf:

```ruby
input {
  pipeline { address => "ns-1-app-1"  }
}

output {
  stdout { codec => rubydebug  }
}
```

pipeline/ns-1-app-2.conf:

```ruby
input {
  pipeline { address => "ns-1-app-2"  }
}

output {
  stdout { codec => rubydebug  }
}
```

- Sample Data:

- Steps to Reproduce:

Start logstash container:

```bash
docker run --rm \
-v $(pwd)/config/logstash.yml:/usr/share/logstash/config/logstash.yml \
-v $(pwd)/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml \
-v $(pwd)/pipeline:/usr/share/logstash/pipeline \
docker.elastic.co/logstash/logstash:7.8.0 
```

Comment out the second pipeline (pipelines.yml):

```yaml
- pipeline.id: ns-1-app-1
  path.config: "/usr/share/logstash/pipeline/ns-1-app-1.conf"
#- pipeline.id: ns-1-app-2
#  path.config: "/usr/share/logstash/pipeline/ns-1-app-2.conf"
```

Watch logstash show logs:

```txt
[2020-06-24T00:58:54,433][INFO ][logstash.javapipeline    ] Pipeline terminated {"pipeline.id"=>"ns-1-app-2"}
[2020-06-24T00:58:54,439][INFO ][logstash.agent           ] Pipelines running {:count=>3, :running_pipelines=>[:"ns-1-app-1", :dispatch, :raw], :non_running_pipelines=>[:"ns-1-app-2"]}
```

Uncomment the second pipeline (pipelines.yml):

```yaml
- pipeline.id: ns-1-app-1
  path.config: "/usr/share/logstash/pipeline/ns-1-app-1.conf"
- pipeline.id: ns-1-app-2
  path.config: "/usr/share/logstash/pipeline/ns-1-app-2.conf"
```

Logstash doesn't print anything. Actually, what ever you do with the second pipeline, Logstash just print log on the first time.
