### ISSUE TITLE
Logstash Failing to Split a large JSON Array

### ISSUE THREAD

**Issue by christophercutajar** [elastic/logstash#13056]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`): Logstash 7.13.2

2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker): Experienced issue both when running logstash via ZIP Archive and Docker

3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes): Experienced issue both when running logstash via command line and in Kubernetes

**OS version** (`uname -a` if on a Unix-like system): MacOS Darwin Kernel Version 20.4.0 & GKE

**Description of the problem including expected versus actual behavior**:

I'm working on a logstash pipeline that splits a JSON array. My pipeline is very simple as is the following:

```
    split {
        field => "[ccm][control-domains]"
    }

    split {
        field => "[ccm][control-domains][controls]"
    }

    split {
        field => "[ccm][control-domains][controls][questions]"
    }

    mutate {
        add_field => { "caiq_version" => "%{[ccm][metadata][version]}" }
        add_field => { "caiq_title" => "%{[ccm][metadata][title]}" }
        add_field => { "caiq_sourcefile" => "%{[ccm][metadata][source-file]}" }
        add_field => { "control-domain-id" => "%{[ccm][control-domains][id]}" }
        add_field => { "control-domain-title" => "%{[ccm][control-domains][title]}" }
        add_field => { "control-domain-control-id" => "%{[ccm][control-domains][controls][id]}" }
        add_field => { "control-domain-control-title" => "%{[ccm][control-domains][controls][title]}" }
        add_field => { "control-domain-control-specification" => "%{[ccm][control-domains][controls][specification]}" }
        add_field => { "control-domain-control-question-id" => "%{[ccm][control-domains][controls][questions][id]}" }
        add_field => { "control-domain-control-question-content" => "%{[ccm][control-domains][controls][questions][content]}" }
    }

    mutate {
        remove_field => ["ccm", "message"]
    }
```

The input is coming from Filebeat which is reading a JSON file and sending it to Logstash. When the input is a JSON file having a small JSON array, the splitting and ingestion are done as expected. Having said that, when using a JSON file having a big JSON array, logstash is throwing the below parse error. I've confirmed that the JSON file is a valid one. 

```
ParserError: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (byte[])"{
  "ccm": {
    "metadata": {
      "version": "3.1",
      "title": "CONSENSUS ASSESSMENTS INITIATIVE QUESTIONNAIRE v3.1",
      "source-file": "official-csa-caiq-elastic-cloud.xlsx"
    },
    "control-domains": [
      {
        "id": "GRM",
        "title": "Governance and Risk Management",
        "controls": [
          {
            "id": "GRM-01",
            "title": "Baseline Requirements",
            "specification": "Baseline security requirements shall be established for developed"[truncated 33255 bytes]; line: 500, column: 15])
 at [Source: (byte[])"{
  "ccm": {
    "metadata": {
      "version": "3.1",
      "title": "CONSENSUS ASSESSMENTS INITIATIVE QUESTIONNAIRE v3.1",
      "source-file": "official-csa-caiq-elastic-cloud.xlsx"
    },
    "control-domains": [
      {
        "id": "GRM",
        "title": "Governance and Risk Management",
        "controls": [
          {
            "id": "GRM-01",
            "title": "Baseline Requirements",
            "specification": "Baseline security requirements shall be established for developed"[truncated 33255 bytes]; line: 500, column: 33771]>}
[2021-07-06T16:11:03,021][WARN ][logstash.filters.split   ][main][462a3955a113ad440ad31788d032c0e49cf9b8d32152094a0920d6ddefe353cc] Only String and Array types are splittable. field:[ccm][control-domains] is of type = NilClass
[2021-07-06T16:11:03,021][WARN ][logstash.filters.split   ][main][656649e4a1e8588a783236906d388f4624ef266c7fd00e8fcc0348cb969a6602] Only String and Array types are splittable. field:[ccm][control-domains][controls] is of type = NilClass
[2021-07-06T16:11:03,022][WARN ][logstash.filters.split   ][main][7666e818a78904332666ab75d770023e24a6fafe547d20b8475b1fb368490b51] Only String and Array types are splittable. field:[ccm][control-domains][controls][questions] is of type = NilClass
```

It is expected that logstash will handle a file having a big JSON array and ingests it into ES similar to what is being done when a JSON file having a small JSON array is being passed to it.

**Steps to reproduce**:

 1. Download Filebeat and Logstash locally and use the following configs

<details>
<summary>filebeat.yaml</summary>

```
# ============================== Filebeat inputs ===============================

filebeat.inputs:

- type: log
  enabled: true
  paths:
    - sample.json
  tags: ["controls"]
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match: after
  processors:
    - decode_json_fields:
        fields : ["message"]
        target: ""
        process_array: true

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false

setup.ilm.enabled: false
setup.template.enabled: false


# ------------------------------ Logstash Output -------------------------------
output.logstash:
  hosts: ["localhost:5014"]
  index: "caiq-controls-test"
  loadbalance: true
  max_retries: 0

```

</details>

<details>
<summary>logstash.conf</summary>

```
input {
  beats {
    ssl => false
    ssl_verify_mode => "none"
    port => 5014
  }
}

filter {
    json {
        source => "message"
    }

    split {
        field => "[ccm][control-domains]"
    }

    split {
        field => "[ccm][control-domains][controls]"
    }

    split {
        field => "[ccm][control-domains][controls][questions]"
    }

    mutate {
        add_field => { "caiq_version" => "%{[ccm][metadata][version]}" }
        add_field => { "caiq_title" => "%{[ccm][metadata][title]}" }
        add_field => { "caiq_sourcefile" => "%{[ccm][metadata][source-file]}" }
        add_field => { "control-domain-id" => "%{[ccm][control-domains][id]}" }
        add_field => { "control-domain-title" => "%{[ccm][control-domains][title]}" }
        add_field => { "control-domain-control-id" => "%{[ccm][control-domains][controls][id]}" }
        add_field => { "control-domain-control-title" => "%{[ccm][control-domains][controls][title]}" }
        add_field => { "control-domain-control-specification" => "%{[ccm][control-domains][controls][specification]}" }
        add_field => { "control-domain-control-question-id" => "%{[ccm][control-domains][controls][questions][id]}" }
        add_field => { "control-domain-control-question-content" => "%{[ccm][control-domains][controls][questions][content]}" }
    }

    mutate {
        remove_field => ["ccm", "message"]
    }
}

output {
  elasticsearch {
    hosts => <elastic_host>
    user => <username>
    password => <password>
    index => "caiq-controls-test"
    document_id => "%{[control-domain-control-question-id]}"
    sniffing => false
  }
}
```
</details>

 2. Start Logstash
 3. Start Filebeat to ingest the sample JSON file. This execution should result in a successful ingestion into ES.

[control-domains-sample.txt](https://github.com/elastic/logstash/files/6777209/control-domains-sample.txt) 
 
 4. Stop Filebeat. Configure filebeat to ingest the full JSON file
 5. Start Filebeat to ingest the full JSON file. This execution should crash logstash and result in black ingestion into ES.

[control-domains-full.json.txt](https://github.com/elastic/logstash/files/6777210/control-domains-full.json.txt)
