### ISSUE TITLE
Add EnvVar to request plugins be installed

### ISSUE THREAD

**Issue by ThorbenJ** [elastic/logstash#15070]
Good day.

Please consider updating the docker image's /usr/local/bin/docker-entrypoint script to include code to install plugins, listed via an envvar, before starting logstash.

Perhaps something like below, with LOGSTASH_PLUGIN_INSTALL being a whitespace separated list:
```
for P in $LOGSTASH_PLUGIN_INSTALL; do
  logstash-plugin install $P
done
```
(^not tested for syntax correctness, or edge cases, but I hope the concept is clear)

It is important that logstash-plugin run without logstash running, and this would be the most friendly way.

You might consider a second loop for LOGSTASH_PLUGIN_REMOVE

Thanks,
Thorben

**Comment by ThorbenJ** [comment]
For more context, here is part of a k8s manifest that I use:

```
...snip...
  startup.sh: |
    #!/bin/sh
    set -e

    logstash-plugin install logstash-filter-elastic_integration

    mkdir -p /usr/share/logstash/data/geoipdb
    find /usr -iname \*geo\*mmdb -type f -exec ln -s \{\} /usr/share/logstash/data/geoipdb/ \;

    exec /usr/local/bin/docker-entrypoint $@
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: tj-logstash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:8.7.1
        command: ['/var/local/startup.sh']
        name: logstash
...snip...
```
