### ISSUE TITLE
Logstash container fails to start

### ISSUE THREAD

**Issue by mohanss08** [elastic/logstash#16563]
My `Elasticsearch, Logstash, and Kibana` stack setup is based on Docker Compose.

`Logstash` container fails to start and throws the following error.

```
logstash  | ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/usr/share/logstash/config, exception=LogStash::ConfigurationError, message=>Cannot evaluate `${xpack.monitoring.elasticsearch.password}`. Replacement variable `xpack.monitoring.elasticsearch.password` is not defined in a Logstash secret store or as an Environment entry and there is no default value given.
logstash  | [FATAL] 2024-10-09 05:30:54.028 [main] Logstash - Logstash stopped processing because of an error: (SystemExit) exit
logstash  | org.jruby.exceptions.SystemExit: (SystemExit) exit
logstash  |     at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:921) ~[jruby.jar:?]
logstash  |     at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:880) ~[jruby.jar:?]
logstash  |     at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:90) ~[?:?]
logstash  | 2024/10/09 05:30:54 Setting 'xpack.monitoring.elasticsearch.password' from environment.
logstash  | 2024/10/09 05:30:54 Setting 'xpack.monitoring.enabled' from environment.
logstash  | 2024/10/09 05:30:54 Setting 'xpack.monitoring.elasticsearch.username' from environment.
logstash  | Using bundled JDK: /usr/share/logstash/jdk
```

It seems that `Logstash` cannot find or evaluate the variable `${xpack.monitoring.elasticsearch.password}` which was working fine before the upgrade. Because it is working fine with `Logstash v8.12.2`.

In the release notes page - [Logstash 8.15.2 Release Notes | Logstash Reference [8.15] | Elastic](https://www.elastic.co/guide/en/logstash/current/logstash-8-15-2.html)

I could see that it is fixed, but I tried with` v8.15.2` but it didn't work as expected like old `v8.12.2`.

Since `Logstash` is functioning properly with `v8.12.2` even though it is stated that it has been resolved with `v8.15.2`, But it is not working correctly as expected. So, please let me know whether I should wait for the next release?

**Comment by jsvd** [comment]
```
logstash  | 2024/10/09 05:30:54 Setting 'xpack.monitoring.elasticsearch.password' from environment.
```
the password seems to be detected correctly from the environment variables, can you show how the docker image is being launched?

**Comment by mohanss08** [comment]
@jsvd My docker-compose file's logstash content given below for your reference.

```
  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    command: sh -c "logstash -f /usr/share/logstash/pipeline/file.conf"
    ports:
      - "5044:5044"
      - "9600:9600" 
    environment:
      - xpack.monitoring.elasticsearch.username=$ELASTIC_USERNAME
      - xpack.monitoring.elasticsearch.password=$ELASTIC_PASSWORD
      - xpack.monitoring.enabled=true
      - 'pipeline.ecs_compatibility:disabled'
    networks:
      - logstash_network
    depends_on:
      - elasticsearch
networks:
  logstash_network:
    driver: bridge
```
Please take a look and let me know if any additional information is required.
