### ISSUE TITLE
plugin install contrib fails

### ISSUE THREAD

**Issue by Akshaykapoor** [elastic/logstash#1658]
Hi,

I installed logstash 1.4.2 via yum on centOS. bin/plugin instal contrib fails saying,

gzip: /opt/logstash/vendor/logstash/logstash-contrib-1.4.2-modified.tar.gz: unexpected end of file
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
cp: cannot stat `/opt/logstash/vendor/logstash/logstash-contrib-1.4.2-modified/*': No such file or directory

Checking in /opt/logstash/lib/logstash/version.rb contains LOGSTASH_VERSION = "1.4.2-modified";

changing that to 1.4.2 and running again works fine with all the plugins getting installed. Could anyone confirm if it's not an issue in the logstash repo ?

Thanks,
Akshay

**Comment by josh-padnick** [comment]
Special thanks to @mose for posting his fix.  For those using SaltStack, this also works:

```yaml
# Fix the Logstash version issue that prevents the contrib plugin from being installed
fix_logstash_version:
  cmd.run:
    - name: sed -i '/1.4.2-modified/c\LOGSTASH_VERSION = "1.4.2"' /opt/logstash/lib/logstash/version.rb

# Install the logstash contrib plugin
install_logstash_contrib_plugin:
  cmd.run:
    - name: /opt/logstash/bin/plugin install contrib
    - unless: "test -e /opt/logstash/lib/logstash/codecs/cloudtrail.rb"
    - require:
      - cmd: fix_logstash_version
```
