### ISSUE TITLE
failing event spec on deserialized json input

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#3018]
the new event spec introduced in #2997 (@talevy) does not work with deserialized json input as exposed with a new event spec strategy to test both normal hash and hash from deserialized json introduced in #2991 

this need to be figured out.

**Comment by colinsurprenant** [comment]
output of the failing test
```
Failures:

  1) LogStash::Event using hash input from deserialized json behaves like all event tests #include? should include field with nil value
     Failure/Error: expect(subject.include?("nilfield")).to be_true
       expected: true value
            got: false
     Shared Example Group: "all event tests" called from ./spec/core/event_spec.rb:452
     # ./spec/core/event_spec.rb:126:in `(root)'
     # ./rakelib/test.rake:20:in `(root)'

Finished in 3.33 seconds
371 examples, 1 failure
```
