### ISSUE TITLE
Logstash_Master_Default_Plugins fails on already fixed plugins

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#4014]
The build fails on plugins that already have been fixed to depend on current logstash-core

Example for latest build: http://build-eu-00.elastic.co/view/LS%20Master/job/Logstash_Master_Default_Plugins/601/console

```
Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-input-couchdb_changes (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-input-couchdb_changes (>= 0) java', in any of the sources.
rake aborted!
```

However logstash-input-couchdb_changes latest gem (https://rubygems.org/gems/logstash-input-couchdb_changes/versions/2.0.1) depends on "logstash-core < 3.0.0, >= 2.0.0.snapshot"

**Comment by purbon** [comment]
working on making this happen, not sure why but the reason looks like having a version conflict over stud dependency.

**Comment by purbon** [comment]
I narrowed down the problem, and it was because of the non released ( __as final release__ ) ```logstash-output-elasticsearch```.

In master if you update the ```Gemfile``` to:

```
diff --git a/Gemfile b/Gemfile
index ae9d703..36ae866 100644
--- a/Gemfile
+++ b/Gemfile
@@ -8,11 +8,112 @@ gem "ci_reporter_rspec", "1.0.0", :group => :development
 gem "simplecov", :group => :development
 gem "coveralls", :group => :development
 gem "rspec", "~> 3.1.0", :group => :development
-gem "logstash-devutils", "~> 0.0.15", :group => :development
+gem "logstash-devutils", "~> 0.0.18", :group => :development
 gem "benchmark-ips", :group => :development
 gem "octokit", "3.8.0", :group => :build
-gem "stud", "~> 0.0.21", :group => :build
+gem "stud", "~> 0.0.22", :group => :build
 gem "fpm", "~> 1.3.3", :group => :build
 gem "rubyzip", "~> 1.1.7", :group => :build
 gem "gems", "~> 0.8.3", :group => :build
 gem "flores", "~> 0.0.6", :group => :development
```

running ```rake plugin:install-default``` will work as expected, however ```rake test:install-default``` will fail and this is because some plugins have the ```logstash-output-elasticsearch``` defined as a development dependency. Until an official version of this plugin gets released for the master branch, this test is not going to pass as the plugin installation don't work with pre releases.

Offender for using ```logstash-output-elasticsearch``` for test is:

```./logstash-input-couchdb_changes/logstash-input-couchdb_changes.gemspec:30:  s.add_development_dependency 'logstash-output-elasticsearch'```

**Comment by purbon** [comment]
Pulling this offenders out and running ```rake test:plugins``` have this output:

```
Failures:

  1) LogStash::Outputs::Statsd registration and close should register without errors
     Failure/Error: Unable to find matching line from backtrace
     SocketError:
       bind: name or service not known
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:17:in `register'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:21:in `run'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:63:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  2) LogStash::Outputs::Statsd#send count metrics should receive data send to the server
     Failure/Error: Unable to find matching line from backtrace
     SocketError:
       bind: name or service not known
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:17:in `register'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:21:in `run'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:63:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  3) LogStash::Outputs::Stdout should register without errors
     Failure/Error: Unable to find matching line from backtrace
     SocketError:
       bind: name or service not known
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:17:in `register'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:21:in `run'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:63:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  4) LogStash::Outputs::Stdout#send sends the generated event out
     Failure/Error: Unable to find matching line from backtrace
     SocketError:
       bind: name or service not known
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:17:in `register'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:21:in `run'
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-2.0.1/spec/spec_helper.rb:63:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  5) LogStash::Inputs::Graphite receive should support using N as current timestamp
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `strftime' for "2015-10-12T13:44:35.640Z":LogStash::Timestamp
     # ./lib/logstash/util/reporter.rb:26:in `report'
     # ./lib/logstash/util/reporter.rb:11:in `start'
     # ./lib/logstash/util/reporter.rb:9:in `start'
``` 
with issues in ```output-statsd``` and ```input-graphite```.
