### ISSUE TITLE
[Master] Default plugins test broken

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4214]
See http://build-eu-00.elastic.co/view/LS%20Master/job/Logstash_Master_Default_Plugins/759/console

```
LogStash::Inputs::Tcp should read plain with unicode
     Failure/Error: Unable to find matching line from backtrace
     Errno::EADDRINUSE:
       Address already in use - bind - Address already in use
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:214:in `new_server_socket'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:75:in `register'
     # ./logstash-core/lib/logstash/pipeline.rb:145:in `start_inputs'
     # ./logstash-core/lib/logstash/pipeline.rb:144:in `start_inputs'
     # ./logstash-core/lib/logstash/pipeline.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.18-java/lib/logstash/devutils/rspec/logstash_helpers.rb:78:in `input'

  2) LogStash::Codecs::RubyDebug#encode should print beautiful hashes
     Failure/Error: subject { LogStash::Codecs::RubyDebug.new }
     NoMethodError:
       undefined method `on_load' for ActiveSupport:Module
     # ./vendor/bundle/jruby/1.9/gems/awesome_print-1.6.1/lib/awesome_print.rb:29:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # ./vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.4/lib/logstash/codecs/rubydebug.rb:1:in `(root)'
     # ./logstash-core/lib/logstash/codecs/base.rb:15:in `initialize'
     # ./vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.4/lib/logstash/codecs/rubydebug.rb:18:in `register'
     # ./vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.4/spec/codecs/rubydebug_spec.rb:7:in `subject'
     # ./vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-2.0.4/spec/codecs/rubydebug_spec.rb:11:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  3) LogStash::Inputs::Syslog should add unique tag when grok parsing fails with live syslog input
     Failure/Error: insist { events[i]["tags"] } == ["_grokparsefailure_sysloginput"]
     Insist::Failure:
       Expected ["_grokparsefailure_sysloginput"], but got nil
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-syslog-2.0.2/spec/inputs/syslog_spec.rb:73:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-syslog-2.0.2/spec/inputs/syslog_spec.rb:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```
