### ISSUE TITLE
incorrect beat config example

### ISSUE THREAD

**Issue by nellicus** [elastic/logstash#4792]
https://www.elastic.co/guide/en/logstash/2.2/advanced-pipeline.html#multiple-input-output-plugins

"This example creates a Logstash pipeline that takes input from a Twitter feed and the Filebeat client, then sends the information to an Elasticsearch cluster as well as writing the information directly to a file."

implies filebeat sending to logstash

then config actually is for sending to elasticsearch

```
filebeat:
  prospectors:
    -
      paths:
        - "/path/to/sample-log" 
      fields:
        type: syslog
output:
  elasticsearch:
    enabled: true
    hosts: ["http://localhost:5043"]
  tls:
    certificate: /path/to/ssl-certificate.crt 
    certificate_key: /path/to/ssl-certificate.key
    certificate_authorities: /path/to/ssl-certificate.crt
    timeout: 15

 Path to the file or files that Filebeat processes.
 Path to the SSL certificate for the Logstash instance.
```

should be

```
output:
  logstash:
    hosts: ["localhost:5043"]
  tls:
    certificate_authorities: ["/etc/pki/root/ca.pem"]
    certificate: "/etc/pki/client/cert.pem"
    certificate_key: "/etc/pki/client/cert.key"
```

?

cc @debadair @palecur
