### ISSUE TITLE
master build failure due to metrics error

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4824]
Hi,
  last master build is broken due to this error, see (http://build-eu-00.elastic.co/view/LS%20Master/job/logstash_regression_master/616/) only heppened for JDK8, but worst investigating. This looks like a rogue thread going on somewhere.

Error is:

```
Failures:

  1) LogStash::Inputs::Metrics#update should fill up the queue with received events
     Failure/Error: expect(queue.count).to eq(1)
       
       expected: 1
            got: 41
       
       (compared using ==)
     # ./logstash-core/spec/logstash/inputs/metrics_spec.rb:29:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:240:in `execute'
```

@ph any idea?
