### ISSUE TITLE
2.x branch regression test broken

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4825]
Hi,
  last two build of the 2.x branch regression test are red due to this error:

```
Failures:

  1) LogStash::Agent#execute when auto_reload is true if state is clean should periodically reload_state
     Failure/Error: expect(subject).to receive(:reload_state!).at_least(3).times
       (#<LogStash::Agent:0x1bb3e150>).reload_state!(any args)
           expected: at least 3 times with any arguments
           received: 2 times with any arguments
     # ./logstash-core/spec/logstash/agent_spec.rb:77:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
```

See http://build-eu-00.elastic.co/view/LS%202.x/job/logstash_regression_2x/111/ for details, for example.

@jsvd as this is bound to reload_state, any idea why this might be happening?
