### ISSUE TITLE
Bug in config parser in 5.0 (seen in CI)

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5464]
Bug seen in Jenkins, see https://logstash-ci.elastic.co/job/elastic+logstash+5.0+multijob-intake/133/console

```
Failures:

  1) LogStashConfigParser when using two plugin sections of the same type (filters) should create a pipeline with both sections
     Failure/Error: expect(outputs.size).to eq(2)
       
       expected: 2
            got: 1
       
       (compared using ==)
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/logstash-core/spec/logstash/config/config_ast_spec.rb:186:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/rakelib/test.rake:42:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:248:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-
```

error seems to be here since https://logstash-ci.elastic.co/job/elastic+logstash+5.0+multijob-intake/130/console and https://github.com/elastic/logstash/commit/ed46e475eabd45d44f566b63d9d9799c66fe15cc
