### ISSUE TITLE
Beats config always locks the log file which I cant edit

### ISSUE THREAD

**Issue by vishnuprasadh** [elastic/logstash#5859]
**I got the configuration for filebeat going for logstash and filebeat.yml  as follows.  The biggest issue is that the log file is locked by filebeat process and am not able to edit it. How do I control this ? Please help, i have tried this for over 3hrs now :-(**

```
input{`
		beats{
			port=>5044
		}
}
	output{
		kafka{
			topic_id=> "accesslogs"
			}
		elasticsearch{
			hosts => ["localhost:9200"]
		}
	}
```

> Filebeat config

```
filebeat:
  prospectors:
     paths:
       "/var/apps/logs/*"
      input_type: log

      close_older: 1m

      document_type: log

      scan_frequency: 10s

      backoff: 1s

      force_close_files: true

   
  
output:
  logstash:
    hosts: ["localhost:5044"]
    worker: 1
    index: filebeat

shipper:
  tags: ["node", "node1"]
  ignore_outgoing: true
  refresh_topology_freq: 10
logging:
  files:
    path: /var/log/mybeat

    name: mybeat

    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 5
```

> 

OS used is as follows:
Version:Macbook OSX
Operating System: 10.10.5
filebeat-1.2.3-darwin is version am using with logstash-2.3.4 and elasticsearch-2.4.0 with kibana-4.6.0
