### ISSUE TITLE
Metrics collection test failed

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6210]
Ref: https://logstash-ci.elastic.co/job/elastic+logstash+5.x+dockerubuntu-periodic/177/console

Snippet of failure:

```
Failures:

  1) LogStash::Pipeline when collecting metrics in the pipeline pipelines populates the pipelines core metrics
     Failure/Error: wait(3).for do
       expected: falsey value
            got: true
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `handle_matcher'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `handle_matcher'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # ./logstash-core/spec/logstash/pipeline_spec.rb:654:in `(root)'
...
```
