### ISSUE TITLE
auto_reload test failed

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6246]
https://logstash-ci.elastic.co/job/elastic+logstash+5.0+multijob-os-compatibility/os=opensuse/233/console

```
Failures:

  1) LogStash::Agent#execute when auto_reload is true if state is clean should periodically reload_state
     Failure/Error: expect(subject).to receive(:reload_state!).at_least(3).times
       (#<LogStash::Agent:0x458babc3>).reload_state!(any args)
           expected: at least 3 times with any arguments
           received: 1 time with any arguments
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-os-compatibility/os/opensuse/logstash-core/spec/logstash/agent_spec.rb:158:in `(root)'
```
