### ISSUE TITLE
Support multiple separate pipelines in a single logstash instance

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6521]
Currently logstash supports running only a single instance of a pipeline, but it would be useful to run multiple pipelines.

Supporting multiple pipelines has several benefits:
 * simplifying event flow conditionals in complex pipeline configs
 * isolating impact of failures and backpressure in multi flow pipelines configs
 * tuning workers, queueing and batching for different event flows

~~The simplest way to implement and use this feature is to add a toggle feature that, when enabled, reads from the `config/logstash.yml` a list of pipelines~~
This feature will have logstash read a `pipelines.yml` file where pipelines can be described individually. Example:

```yaml
# pipelines.yml
- pipeline.id: line
  config.string: "input { generator {} } filter { sleep { time => 0.01 } } output { stdout { codec => line { format => '%{sequence}' } } }"
  pipeline.workers: 1
- pipeline.id: line2
  path.config: "/etc/conf.d/logstash/line2.*.cfg"
  pipeline.workers: 5
```

TODO:

- [x] define set of configurable settings per pipeline https://github.com/elastic/logstash/issues/6492
- [x] enforce validation of set of configurable settings per pipeline https://github.com/elastic/logstash/issues/6541
- [x] make queue path depend on pipeline id https://github.com/elastic/logstash/issues/6513
- [x] make metrics api work with multi pipeline https://github.com/elastic/logstash/issues/6531
- [x] make -e and -f mutually exclusive https://github.com/elastic/logstash/pull/6976
- [x] don't concatenate default plugins on -f https://github.com/elastic/logstash/pull/6974
- [x] reload pipeline if pipeline settings changed https://github.com/elastic/logstash/pull/7073

Check the feature branch [feature/multi_pipeline](https://github.com/elastic/logstash/tree/feature/multi_pipeline) or [pr #6525](https://github.com/elastic/logstash/pull/6525) for progress
