### ISSUE TITLE
Test failure: ./logstash-core/spec/logstash/pipeline_spec.rb:255

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6855]
Build failure: https://logstash-ci.elastic.co/job/elastic+logstash+5.x+dockerubuntu-periodic/1544/console

Snippet:

```
Failures:

  1) LogStash::Pipeline defaulting the pipeline workers based on thread safety when there are threadsafe filters only starts multiple filter threads
     Failure/Error: expect(pipeline.worker_threads.size).to eq(worker_thread_count)
       
       expected: 5
            got: 8
       
       (compared using ==)
     # ./logstash-core/spec/logstash/pipeline_spec.rb:255:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:37:in `(root)'
...

```

The failing test code: https://github.com/elastic/logstash/blob/5.x/logstash-core/spec/logstash/pipeline_spec.rb#L255

```
 expect(pipeline.worker_threads.size).to eq(worker_thread_count)
```

I spent a few minutes looking at this:

* [`worker_thread_count` is set to 5 by the test](https://github.com/elastic/logstash/blob/5.x/logstash-core/spec/logstash/pipeline_spec.rb#L88)
* [And then uses `allow` to override the default pipeline.workers value](https://github.com/elastic/logstash/blob/5.x/logstash-core/spec/logstash/pipeline_spec.rb#L95-L96) with `worker_thread_count`
* And yet, the test fails because we expected 5 (`worker_thread_count`) but got 8 (probably computed by how many cores are on the test system).

This smells like a monkeypatch effort by rspec (via `allow`) gone wrong.
