### ISSUE TITLE
Test failure: upgrade_pipeline expected to be called, but was not.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6869]
Build failure: https://logstash-ci.elastic.co/job/elastic+logstash+5.1+dockerubuntu-periodic/1260/console

```
Failures:

  1) LogStash::Agent#execute when auto_reload is false when calling reload_pipeline! with a config that does not contain reload incompatible plugins does upgrade the new config
     Failure/Error: expect(subject).to receive(:upgrade_pipeline).once.and_call_original
       (#<LogStash::Agent:0x1b8ea163>).upgrade_pipeline(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./logstash-core/spec/logstash/agent_spec.rb:139:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:49:in `(root)'
```
