### ISSUE TITLE
Test failure: pipeline 'main' not found in some node stats tests

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7388]
https://logstash-ci.elastic.co/job/elastic+logstash+feature-9000+dockerubuntu-periodic/100/console

10 failures all looking like this: `Expected to find value 'main' in structure ...`

```
  10) LogStash::Api::Modules::NodeStats GET /pipelines should set 'pipelines.main.events.queue_push_duration_in_millis' at '/pipelines' to be a 'Numeric'
      Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
        Expected to find value 'main' in structure '{"test-dlq"=>{"events"=>{"duration_in_millis"=>90, "in"=>100, "filtered"=>100, "out"=>100, "queue_push_duration_in_millis"=>9}, "plugins"=>{"inputs"=>[{"id"=>"api-generator-pipeline", "events"=>{"out"=>100, "queue_push_duration_in_millis"=>9}, "name"=>"generator"}], "filters"=>[], "outputs"=>[{"id"=>"df347d769bc959372f8cc0eed3f262d56dc4536e-2", "events"=>{"duration_in_millis"=>7, "in"=>100, "out"=>100}, "name"=>"dummyoutput"}]}, "reloads"=>{"last_error"=>nil, "successes"=>0, "last_success_timestamp"=>nil, "last_failure_timestamp"=>nil, "failures"=>0}, "queue"=>{"type"=>"memory_acked"}}}', but could not. Payload was '{"host"=>"c33bd450af15", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"c641fa75-87f4-462c-b62b-8b06b416f4d5", "name"=>"c33bd450af15", "pipelines"=>{"test-dlq"=>{"events"=>{"duration_in_millis"=>90, "in"=>100, "filtered"=>100, "out"=>100, "queue_push_duration_in_millis"=>9}, "plugins"=>{"inputs"=>[{"id"=>"api-generator-pipeline", "events"=>{"out"=>100, "queue_push_duration_in_millis"=>9}, "name"=>"generator"}], "filters"=>[], "outputs"=>[{"id"=>"df347d769bc959372f8cc0eed3f262d56dc4536e-2", "events"=>{"duration_in_millis"=>7, "in"=>100, "out"=>100}, "name"=>"dummyoutput"}]}, "reloads"=>{"last_error"=>nil, "successes"=>0, "last_success_timestamp"=>nil, "last_failure_timestamp"=>nil, "failures"=>0}, "queue"=>{"type"=>"memory_acked"}}}}'
      # ./spec/support/resource_dsl_methods.rb:67:in `block in test_api'
      # ./spec/support/resource_dsl_methods.rb:65:in `block in test_api'
      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /tmp/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
      # ./lib/bootstrap/rspec.rb:13:in `<main>'
```

10 failures:

```
2605 examples, 10 failures, 3 pending

Failed examples:

rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:2:38] # LogStash::Api::Modules::NodeStats GET / should set 'pipelines.main.events.out' at '/' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:2:39] # LogStash::Api::Modules::NodeStats GET / should set 'pipelines.main.events.queue_push_duration_in_millis' at '/' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:2:35] # LogStash::Api::Modules::NodeStats GET / should set 'pipelines.main.events.duration_in_millis' at '/' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:2:37] # LogStash::Api::Modules::NodeStats GET / should set 'pipelines.main.events.filtered' at '/' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:2:36] # LogStash::Api::Modules::NodeStats GET / should set 'pipelines.main.events.in' at '/' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:5:4] # LogStash::Api::Modules::NodeStats GET /pipelines should set 'pipelines.main.events.in' at '/pipelines' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:5:3] # LogStash::Api::Modules::NodeStats GET /pipelines should set 'pipelines.main.events.duration_in_millis' at '/pipelines' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:5:6] # LogStash::Api::Modules::NodeStats GET /pipelines should set 'pipelines.main.events.out' at '/pipelines' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:5:5] # LogStash::Api::Modules::NodeStats GET /pipelines should set 'pipelines.main.events.filtered' at '/pipelines' to be a 'Numeric'
rspec ./logstash-core/spec/logstash/api/modules/node_stats_spec.rb[1:5:7] # LogStash::Api::Modules::NodeStats GET /pipelines should set 'pipelines.main.events.queue_push_duration_in_millis' at '/pipelines' to be a 'Numeric'
```

**Comment by jordansissel** [comment]
https://logstash-ci.elastic.co/job/elastic+logstash+master+dockerubuntu-periodic/2344/console

```
Failures:

  1) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.workers' at '/pipelines' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  2) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.config_reload_interval' at '/pipelines' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  3) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.batch_delay' at '/pipelines' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  4) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.config_reload_automatic' at '/pipelines' to be a 'Boolean'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  5) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.batch_size' at '/pipelines' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  6) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.workers' at '/' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}, "os"=>{"name"=>"Linux", "arch"=>"amd64", "version"=>"4.4.0-66-generic", "available_processors"=>4}, "jvm"=>{"pid"=>677, "version"=>"1.8.0_121", "vm_version"=>"1.8.0_121", "vm_vendor"=>"Oracle Corporation", "vm_name"=>"OpenJDK 64-Bit Server VM", "start_time_in_millis"=>1497025016458, "mem"=>{"heap_init_in_bytes"=>268435456, "heap_max_in_bytes"=>1038876672, "non_heap_init_in_bytes"=>2555904, "non_heap_max_in_bytes"=>0}, "gc_collectors"=>["ParNew", "ConcurrentMarkSweep"]}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  7) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.config_reload_interval' at '/' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}, "os"=>{"name"=>"Linux", "arch"=>"amd64", "version"=>"4.4.0-66-generic", "available_processors"=>4}, "jvm"=>{"pid"=>677, "version"=>"1.8.0_121", "vm_version"=>"1.8.0_121", "vm_vendor"=>"Oracle Corporation", "vm_name"=>"OpenJDK 64-Bit Server VM", "start_time_in_millis"=>1497025016458, "mem"=>{"heap_init_in_bytes"=>268435456, "heap_max_in_bytes"=>1038876672, "non_heap_init_in_bytes"=>2555904, "non_heap_max_in_bytes"=>0}, "gc_collectors"=>["ParNew", "ConcurrentMarkSweep"]}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  8) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.config_reload_automatic' at '/' to be a 'Boolean'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}, "os"=>{"name"=>"Linux", "arch"=>"amd64", "version"=>"4.4.0-66-generic", "available_processors"=>4}, "jvm"=>{"pid"=>677, "version"=>"1.8.0_121", "vm_version"=>"1.8.0_121", "vm_vendor"=>"Oracle Corporation", "vm_name"=>"OpenJDK 64-Bit Server VM", "start_time_in_millis"=>1497025016458, "mem"=>{"heap_init_in_bytes"=>268435456, "heap_max_in_bytes"=>1038876672, "non_heap_init_in_bytes"=>2555904, "non_heap_max_in_bytes"=>0}, "gc_collectors"=>["ParNew", "ConcurrentMarkSweep"]}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  9) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.batch_size' at '/' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}, "os"=>{"name"=>"Linux", "arch"=>"amd64", "version"=>"4.4.0-66-generic", "available_processors"=>4}, "jvm"=>{"pid"=>677, "version"=>"1.8.0_121", "vm_version"=>"1.8.0_121", "vm_vendor"=>"Oracle Corporation", "vm_name"=>"OpenJDK 64-Bit Server VM", "start_time_in_millis"=>1497025016458, "mem"=>{"heap_init_in_bytes"=>268435456, "heap_max_in_bytes"=>1038876672, "non_heap_init_in_bytes"=>2555904, "non_heap_max_in_bytes"=>0}, "gc_collectors"=>["ParNew", "ConcurrentMarkSweep"]}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

  10) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.batch_delay' at '/' to be a 'Numeric'
     Failure/Error: expect(acc.has_key?(v)).to eql(true), "Expected to find value '#{v}' in structure '#{acc}', but could not. Payload was '#{payload}'"
       Expected to find value 'main' in structure '{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}', but could not. Payload was '{"host"=>"f5fe6ddc58ed", "version"=>"6.0.0-alpha3", "http_address"=>"127.0.0.1:9600", "id"=>"bc72eadc-5716-4e3d-bb75-e09886ec3b97", "name"=>"f5fe6ddc58ed", "pipelines"=>{"test-dlq"=>{"workers"=>2, "batch_size"=>125, "batch_delay"=>5, "config_reload_automatic"=>false, "config_reload_interval"=>3}}, "os"=>{"name"=>"Linux", "arch"=>"amd64", "version"=>"4.4.0-66-generic", "available_processors"=>4}, "jvm"=>{"pid"=>677, "version"=>"1.8.0_121", "vm_version"=>"1.8.0_121", "vm_vendor"=>"Oracle Corporation", "vm_name"=>"OpenJDK 64-Bit Server VM", "start_time_in_millis"=>1497025016458, "mem"=>{"heap_init_in_bytes"=>268435456, "heap_max_in_bytes"=>1038876672, "non_heap_init_in_bytes"=>2555904, "non_heap_max_in_bytes"=>0}, "gc_collectors"=>["ParNew", "ConcurrentMarkSweep"]}}'
     # ./spec/support/resource_dsl_methods.rb:67:in `test_api'
     # ./spec/support/resource_dsl_methods.rb:65:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'
```
