### ISSUE TITLE
Test failure: LogStash::Timestamp constructor test failure

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7390]
https://logstash-ci.elastic.co/job/elastic+logstash+feature-9000+dockerubuntu-periodic/88/console

```
Failures:

  1) LogStash::Timestamp constructors should work
     Failure/Error: expect(t.time).to eq(now)

       expected: 2017-06-07 19:05:16.271999999 +0000
            got: 2017-06-07 19:05:16.271000000 +0000

       (compared using ==)
     # ./logstash-core/spec/logstash/timestamp_spec.rb:17:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /tmp/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
```
