### ISSUE TITLE
Multiline Parsing with multiple types of logs

### ISSUE THREAD

**Issue by MirkoMorello** [elastic/logstash#8501]
I have some problems parsing different type of logs, for example mongodb and uwsgi, the problem is that in the logstash .conf i can't create **_if_** statements for checking if a log is uwsgi or mongo and need to be filtered with the multiline codec or viceversa. 
i have 1 logstash, 1 filebeat and a number of logs.

- Version: 5.5.0
- Operating System: centos 7
- Config File:
filebeat.yml contains:
```
filebeat.prospectors:

_uwsgi (multiline logs):_

- input_type: log
  paths:
    - /var/log/supervisor/uwsgi.log
  fields:
    - tool: uwsgi
    - version: 1.0.0




_mongodb (single line logs):_

- input_type: log
  paths:
    - /var/log/supervisor/mongo.log
  fields:
    - tool: mongo
    - version: 2.6.12
```

- Sample Data:
mongo log:
`2017-10-19T15:21:53.295+0000 [conn8971713] end connection 127.0.0.1:34527 (19 connections now open)`

uwsgi log:
```
2017-10-19 08:40:00,784 - root - INFO - Device Auth Username guest dont follow <model-name>/<device-name>, denying it
[pid: 32652|app: 0|req: 51694/213138] 127.0.0.1 () {28 vars in 399 bytes} [Thu Oct 19 08:40:00 2017] GET /amqp_auth/login?username=guest&password=guest => generated 4 bytes in 7 msecs (HTTP/1.0 200) 2 headers in 78 bytes (1 switches on $
```

What should i do?
