### ISSUE TITLE
modules ssl.enabled settings expect string values only

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#8580]
Currently the `ssl.enabled` settings for the elasticsearch and kibana module properties [do a comparison with the `"true"` string to determine if ssl should be enabled](https://github.com/elastic/logstash/blob/v5.6.3/logstash-core/lib/logstash/elasticsearch_client.rb#L32)

This works well if the settings are configured through the command line where everything is a string. But if the module is configured through the yaml setting, like, for example:

```yaml
modules:
- name: netflow
  var.elasticsearch.hosts: "node01"
  var.elasticsearch.ssl.enabled: true
```

Then the setting will have a boolean value instead of string, which means that regardless of true or false, the ssl won't be enabled.
