### ISSUE TITLE
modules not start if "config.reload.automatic: true" in logstash v6.0.1

### ISSUE THREAD

**Issue by imweijh** [elastic/logstash#8821]
- Version: 
logstash v6.0.1

- Operating System: 
CentOS 6

- Config File : 
grep -v "#" /etc/logstash/logstash.yml |grep -v "^$"
```
path.data: /var/lib/logstash
config.reload.automatic: true    # this setting will cause logstash endless print "Ignoring the 'pipelines.yml' file because modules or command line ..."
modules:
  - name: netflow
    var.input.udp.port: 2056
path.logs: /var/log/logstash

```
- Steps to Reproduce:
```
enable netflow modules
enable config.reload.automatic
initctl start logstash 
tail -F logstash-plain.log

```

- Work around:
use default setting
config.reload.automatic: false
