### ISSUE TITLE
logstash output files out of order

### ISSUE THREAD

**Issue by geekwolf** [elastic/logstash#9022]
- logstash 6.1.2、filebeat 6.1.1
- Debian 8 x64
- filebeat
```
filebeat.prospectors:
- type: log
  paths:
    - /home/og/*
  scan_frequency: 20s
  encoding: utf-8
  tail_files: true
  harvester_buffer_size: 5485760
fields:
  ip_address: 192.168.104.125
  env: qa

output.redis:
  hosts: ["1.1.1.1:6379"]
  password: "test"
  key: "filebeat"
  db: 0
  timeout: 5
  max_retries: 3
  worker: 2
  bulk_max_size: 2048
```
- logstash:
cat /etc/logstash/conf.d/logstash.conf

```
input {
  redis {
    batch_count => 4096
    data_type => "list"
    key => "filebeat"
    host => "127.0.0.1"
    port => 6379
    password => "test"
    db => 0 
    threads => 1
   }
}
filter {
  ruby {
      code => 'event.set("filename",event.get("source").split("/")[-1])'
  }
  ruby {
      code => 'event.set("daytime",Time.now.strftime("%Y-%m-%d"))'
  }
}
output {

  if [filename] =~ "nohup" {
    file {
        path => "/data/logs/%{[fields][env]}/%{daytime}/%{[fields][ip_address]}/%{filename}"
        flush_interval => 5
        codec => line { format => "%{message}"}
    }
  } else {
    file {
         path => "/data/logs/%{[fields][env]}/%{daytime}/%{[fields][ip_address]}/logs/%{filename}"
         flush_interval => 5
         codec => line { format => "%{message}"}
   }
 }
}
```

cat /etc/logstash/logstash.yml
```
path.data: /var/lib/logstash
pipeline.workers: 1
pipeline.output.workers: 1
path.config: /etc/logstash/conf.d/*.conf
log.level: warn
path.logs: /var/log/logstash
```

**Problem:**
I've set  pipeline.workers 1 ,but the output files still exist disorder,what should I do?thx
for example:
```
source files:
2018-1-24 11:10:00 xxxx
2018-1-24 11:10:01 xxxx
2018-1-24 11:12:00 xxxx
but the archived files wrong order:
2018-1-24 11:12:00 xxxx
2018-1-24 11:10:00 xxxx
2018-1-24 11:10:01 xxxx
```
