### ISSUE TITLE
Failed to create monitoring event during  logstash startup

### ISSUE THREAD

**Issue by vbohata** [elastic/logstash#9126]
During LS startup I can see following message multiple times:

> [logstash.inputs.metrics  ] Failed to create monitoring event {:message=>"undefined method `ephemeral_id' for nil:NilClass", :error=>"NoMethodError"}

After some time it is OK, monitoring data is in ES. I am using PKI authentication for Logstash to Elasticsearch, so maybe it is related to this.

**Comment by marioluan** [comment]
Can you provide information ref. your setup (LS, ES, OS, etc)?

**Comment by vbohata** [comment]
All 6.x LS affected. Currently I am using LS 6.2.1.
Logstash in CentOS 7 docker containers, custom images using standard LS + some additional plugins + docker healthcheck using trying to read "http://127.0.0.1:9600/_node/stats/events" each 30 seconds.
ES 6.2.1

xpack monitoring conf in logstash.yml:
```
xpack:
    monitoring:
        elasticsearch:
            password: ''
            ssl:
                ca: ${LOGSTASH_CONFIG_PATH}/certs/cacert.crt
                keystore:
                    password: mypass
                    path: ${LOGSTASH_CONFIG_PATH}/certs/mycert.jks
            url:
            - es1.mydomain:9200
            - es2.mydomain:9200
            - es3.mydomain:9200
            username: ''
        enabled: true
```
