### ISSUE TITLE
Logstash keystore can become corrupt.

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#9581]
From a provided keystore example it appears that a keystore, when no password is set may become corrupt at no fault of the user.  After many attempts to cause a corruption, I could not reproduce.

However, based on the example provided, I was able to tell that for some reason (unknown) the keystore can terminate in a `A0` byte, not the expected `00` byte. When this happens it can cause the meta information we store at the end of the keystore to become corrupt.  

After debugging the provided example, (for reasons unknown), the os file stream is not actually at the end of the file after instructing the keystore to `store`.  This results in this data being written near the end of the file, but not actually at the end of the file as expected, and this specifically is the corruption. I am unsure how or why that byte stream/keystore.store causes the file output to be near, but not at the end of the file. All attempts to reproduce show the data landing correctly at the end of the file. 
```
 keyStore.store(os, keyStorePass);
 if (useDefaultPass) {
    byte[] obfuscatedPass = SecretStoreUtil.asciiCharToBytes(SecretStoreUtil.obfuscate(keyStorePass.clone()));
     DataOutputStream dataOutputStream = new DataOutputStream(os);
     os.write(obfuscatedPass);
     dataOutputStream.write(obfuscatedPass.length); // 1 byte integer
```

As a work around, I attempted to ensure that keystore os filestream was closed prior to writing the metadata, and used a different output stream to append to the file. This seems to work for all cases, including the one un-reproducible example case. 

If this happens the specific error is : 
```
[ERROR] 2018-05-15 16:52:32.696 [main] secretstorecli - Found a file at /etc/logstash/logstash.keystore, but it is not a valid Logstash keystore. {:cause=>java.io.IOException: Integrity check failed: java.io.IOException: getSecretKey failed: Password is not ASCII, :backtrace=>["org.logstash.secret.store.backend.JavaKeyStore.load(org/logstash/secret/store/backend/JavaKeyStore.java:265)", 
```
...and is only applicable when not using an explicit password.

**Comment by deepybee** [comment]
Superb debugging, thanks!

**Comment by bphenriques** [comment]
Hello, I am going to resurface this again :smile: 

**Version**: Logstash 6.6.0
**Environment**: Setting up Logstash using Ansible Scripts
**Reproduce**: Access logstash container (created by Molecule) and `/usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash/ add my-key`

Ansible script to setup the keystore:
```
---

- name: Setup Logstash's keystore
  block:
  - name:  Setup Logstash keystore.
    shell: /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash/ create
    environment:
      LOGSTASH_KEYSTORE_PASS: "{{ logstash.configs.security.keystore_pass }}"

  tags:
    - logstash.configure.keystore
```

Defaults:
```
---
logstash:
    (...)
    security:
      keystore_pass: changeme
```

Exception:
```
  - name:  Setup Logstash keystore.
    shell: /usr/share/logstash/bin/logstash-keystore --path.settings /etc/logstash/ create
    environment:
      LOGSTASH_KEYSTORE_PASS: "{{ logstash.configs.security.keystore_pass }}"
```
