### ISSUE TITLE
Logstash container immediately terminates

### ISSUE THREAD

**Issue by mhyousefi** [elastic/logstash#9873]
I am trying to run the ELK stack using official docker images on Docker Hub. I have the following for my `docker-compose.yml`:

```
version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: logstash
    command: bash -c "logstash -f absolute/path/to/my/project-dir/logstash.conf"
    depends_on:
      - elasticsearch
  kibana:
    image: kibana
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearc
```

And at my `ogstash.conf` looks like this:

```
input { stdin {} }

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
  }
}
```

Now when I run `docker-compose up`, all containers are run flawlessly. However, `logstash` is terminated with the following error:

```Pipeline has terminated {:pipeline_id=>".monitoring-logstash", :thread=>"#<Thread:0x6cb098cd run>"}```

The following image shows more of my terminal log:

![Terminal Logs](https://image.ibb.co/njsqiz/ERROR.png)

I appreciate any help!

Here are some extra info:
`Docker version 18.06.0-ce, build 0ffa825`
`docker-compose version 1.8.0, build unknown`
I am running `Ubuntu 16.04`
