### ISSUE TITLE
Pipeline-to-Pipeline Communication - Persist @meatadata through pipelines outputs

### ISSUE THREAD

**Issue by berglh** [elastic/logstash#9884]
- Version: 6.3.2
- Operating System: OEL 7.3
- Config File: It's complicated
- Steps to Reproduce:
  1. Wire up a pipeline chain: `inputs` => `processing` => `outputs`
  2. In inputs set some metadata values based on some environment variables
  3. In processing set some conditional filtering on `[@metadata]` fields
  4. Watch things not happen because the `[@metadata]` fields have been dropped before `processing`
- Reasoning:
Metadata is dropped at the before hitting outputs; unless using rubydebug codec.

>In Logstash 1.5 and later, there is a special field called @metadata. The contents of @metadata will not be part of any of your events at output time, which makes it great to use for conditionals, or extending and building event fields with field reference and sprintf formatting.

- Workaround Tried:
I tried to mutate rename the `@metadata` map to a persistent metadata object/map however this seemed to not copy the hash structure across. It's possible to take the contents of `%{@metadata}`, assign it to a field, then parse it with `logstash-filter-json` to a temporary working object; then to copy the temporary object back to the `@metadata` hash in the next pipeline. This is seems like a pretty long winded approach to persist the metadata between the pipelines.

My next test will try to output and input as rubydebug codec and outputting the metadata, but this kind of seems a little bit wasteful too; I've not really thought in depth about or know which approach would be less intensive in terms of marshalling/unmarshalling rubydebug/json structures.

- Thoughts:
Yes; I *could* adapt to using a specific object for metadata and drop it explicitly at the end of the output pipeline, but this use case kind of invalidates the use of @metadata in the multiple processing pipeline architecture. 

At the same time; we can't assume people would want to keep @metadata between pipelines, so *if* the pipeline plugs were to support this, it would need to be an option, disabled by default, in the pipeline plugin specifically.

**Comment by danhermann** [comment]
@berglh, I'm unable to reproduce this problem in version 7.0 of Logstash (though there have been no intentional changes to this feature since 6.3). If I create the series of pipelines below, everything functions as expected and the output shows that the events retained the metadata added in the middle pipeline. Could you provide more information on how metadata is not being retained as you would expect?

`generator` pipeline
```
input {
    generator {
      id => gen1
      threads => 1
      message => "generator1"
      count => 5
    }
}
output {
    pipeline {
        send_to => f1
    }
}
```

`f1` pipeline:
```
input {
    pipeline {
        address => f1
    }
}
filter {
    mutate {
        add_field => {"[@metadata][foo]" => "bar"}
    }
}
output {
    pipeline {
        send_to => outputs
    }
}
```

`outputs` pipeline:
```
input {
    pipeline {
        address => outputs
    }
}
output {
    if ([@metadata][foo]) {
      stdout{ codec=>rubydebug {metadata => true} }
    }
}

```

**Comment by berglh** [comment]
@danhermann I'm currently on Logstash 6.5.3, I haven't had a chance to retest this problem. How I circumvented it was by the following config. Can you advise what is the best codec to use for optimum performance between pipelines? I'm assuming there will always be a de/serialisation penalty, maybe some codecs are lighter touch?

```ruby
output {
  if [service] == "usg-syslog" {
    pipeline {
      send_to => "6-syslog"
      codec => rubydebug { metadata => true } 
    }
  } else if [service] == "radius" {
    pipeline {
      send_to => "5-radius" 
      codec => rubydebug { metadata => true } 
    }
  } else if [service] == "ldap" {
    pipeline {
      send_to => "3-ldap"
      codec => rubydebug { metadata => true } 
    }
  } else if [service] == "dhcpd" {
    pipeline {
      send_to => "4-dhcp-dns" 
      codec => rubydebug { metadata => true } 
    }
  } else if [service] == "dns-authoritative" {
    pipeline {
      send_to => "4-dhcp-dns" 
      codec => rubydebug { metadata => true } 
    }
  } else {
    pipeline {
      send_to => "2-general"
      codec => rubydebug { metadata => true } 
    }
  }
}
```

Example input for a processing pipeline:
```ruby
input {
  pipeline {
    address => "2-general"
    add_field => { "[@metadata][pipeline]" => "general" }
    codec => rubydebug { metadata => true }
  }
}
```
I was was generating some metadata fields using environment variables in the logstash container:
```ruby
filter {
  mutate {
    add_field => [
      "[@metadata][ls-dev-mode]", "${LS_DEV_MODE:true}",
      "[@metadata][ls-dev-input]", "${LS_DEV_INPUT:stdin}",
      "[@metadata][ls-dev-output]", "${LS_DEV_OUTPUT:stdout}", 
      "[@metadata][ls-dev-codec]", "${LS_DEV_CODEC:json}",
      "[@metadata][ls-prod-sample]", "${LS_PROD_SAMPLE:false}"
    ]
  }
}
```
These values were not being parsed and would cause the pipelines to not work correctly on conditionals based upon these values.

I will give your reduced config a run with our current version and see what I see.

Thanks for following up.

**Comment by berglh** [comment]
![image](https://user-images.githubusercontent.com/12455338/56935024-fafd8900-6b31-11e9-9f2d-356939fba0ba.png)

Current pipeline to pipeline architecture for your reference. Here is my pipeline config file:
```yaml
# inputs acts as a router to specific processing pipelines
# reducing the workers on a per pipeline bases greatly reduced the
# number of each plugin instance from running and improves start-up time
- pipeline.id: 1-inputs
  pipeline.workers: 3
  path.config: "/usr/share/logstash/pipelines/1-inputs"
  config.reload.automatic: true
- pipeline.id: 2-general
  pipeline.workers: 2
  path.config: "/usr/share/logstash/pipelines/2-general"
- pipeline.id: 3-ldap
  pipeline.workers: 4
  path.config: "/usr/share/logstash/pipelines/3-ldap"
- pipeline.id: 4-dhcp-dns
  pipeline.workers: 3                               
  path.config: "/usr/share/logstash/pipelines/4-dhcp-dns"
- pipeline.id: 5-radius
  pipeline.workers: 2                               
  path.config: "/usr/share/logstash/pipelines/5-radius"
- pipeline.id: 6-syslog
  pipeline.workers: 4                               
  path.config: "/usr/share/logstash/pipelines/6-syslog"
# there are generic post-processing filters in the output pipeline
- pipeline.id: 7-outputs
  pipeline.workers: 15                               
  config.reload.automatic: true
  path.config: "/usr/share/logstash/pipelines/7-outputs"
```
